### ISSUE TITLE
Please consider this issue!

### ISSUE THREAD

**Issue by quiddy1618** [AzarrAb00ser/TrujkontSecurity#2]
Please don't use C#. It's very gay. As well as you.

Sincerely.

**Comment by AzarrAb00ser** [comment]
it's ok to be gay

kind regards

**Comment by quiddy1618** [comment]
czemu zamknoles to isszue dbeilu

**Comment by quiddy1618** [comment]
otwieraj bo ci jebne

**Comment by AzarrAb00ser** [comment]
no bo nim jestem dbielu

**Comment by AzarrAb00ser** [comment]
ok już otwieram

**Comment by AzarrAb00ser** [comment]
ok narzekaj

**Comment by quiddy1618** [comment]
napisales kiedy interrut routine?

**Comment by AzarrAb00ser** [comment]
co?

**Comment by quiddy1618** [comment]
haha bk z ciebie
https://www.youtube.com/watch?v=m0eDh88UaAo

**Comment by AzarrAb00ser** [comment]
X D
